services:
  - type: web
    name: dash-bot
    env: python
    region: frankfurt   # Կարող ես փոխել օրինակ: singapore / ohio / frankfurt
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: BOT_TOKEN
        sync: false  # Token-ը դնում ես Render dashboard-ում Environment Variables բաժնում
